
networks:
  app-network:
    external: true

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - app-network

  redis-insight:
    container_name: redis-insight
    image: redis/redisinsight:latest
    ports:
      - "8001:8001"
    networks:
      - app-network
